
enum	KETSTASTE	{	KS_NONE,	KS_DOWN,	KS_ONCE,	KS_UP	};

enum	OBJID		{ OI_GROUND, OI_MONSTERSPAWN, OI_PLAYER, OI_SUB_PLAYER, 
	OI_MONSTER, OI_REDCELL, OI_WHITECELL, OI_VIRUS, OI_CANCER, OI_BACTERIA, OI_BULLET, OI_ITEM,
	OI_BACKUI, OI_GAUGE_UI, OI_BUTTON, OI_FADE,
	OI_ENEMYBULLET, OI_EFFECT, OI_SMOOTH, OI_TIMER, OI_MAX	};

enum	SHADERID	{	SI_TOON,	SI_ALPHA,	SI_MAX	};

enum	TIMERTYPE	{	TT_SHOT,	TT_MULTI, TT_GROW,	TT_SPAWN, TT_POWER, TT_DELETE	};

enum	SCENEID		{	SI_HOME,	SI_PLAY };